### ISSUE TITLE
Using Nginx Unit with a ReadOnly filesystem.

### ISSUE THREAD

**Issue by langchain-infra** [nginx/unit#1144]
Hi all,

Trying to use Nginx unit on a read only filesystem with kubernetes and this doesn't seem to work? When I run my container with no tmp dirs mounted, I run into the following error(which is expected:

```
backend-cf448fcd7-z9z5c backend 2024/02/20 20:41:33 [alert] 9#9 Unable to create certificates storage directory: mkdir(/var/lib/unit/certs/) failed (30: Read-only file system)
backend-cf448fcd7-z9z5c backend 2024/02/20 20:41:33 [alert] 9#9 Unable to create scripts storage directory: mkdir(/var/lib/unit/scripts/) failed (30: Read-only file system)
backend-cf448fcd7-z9z5c backend 2024/02/20 20:41:33 [alert] 9#9 bind(6, unix:/var/run/control.unit.sock.tmp) failed (30: Read-only file system)
```
When I try to mount tmp dirs for the container to use doing something like this:

```
    volumes:
      - name: certs
        emptyDir: {}
      - name: scripts
        emptyDir: {}
      - name: control
        emptyDir: {}
    volumeMounts:
      - name: certs
        mountPath: /var/lib/unit/certs
      - name: scripts
        mountPath: /var/lib/unit/scripts
      - name: control
        mountPath: /var/run
```
I then run into an error where the entrypoint doesn't actually perform initialization due to the /var/lib/unit having values inside.
```
/usr/local/bin/docker-entrypoint.sh: /var/lib/unit/ is not empty, skipping initial configuration...
2024/02/20 20:44:49 [info] 1#1 unit 1.31.1 started
2024/02/20 20:44:49 [info] 9#9 discovery started
2024/02/20 20:44:49 [notice] 9#9 module: python 3.11.8 "/usr/lib/unit/modules/python3.unit.so"
2024/02/20 20:44:49 [info] 1#1 controller started
2024/02/20 20:44:49 [notice] 1#1 process 9 exited with code 0
2024/02/20 20:44:49 [info] 11#11 router started
2024/02/20 20:44:49 [info] 11#11 OpenSSL 1.1.1w  11 Sep 2023, 1010117f
```

Is the only way around this overriding the entrypoint script? I would just remove the check on the directory being full but worried that this may have some unforeseen consequences? Any guidance would be appreciated! Separately, is there a way to add a config without having to curl the control endpoint? We could potentially use that option instead as well!
