### ISSUE TITLE
Docker image nginx/unit:1.5-ruby2.3 doesn't have any module available

### ISSUE THREAD

**Issue by chapuzzo** [nginx/unit#179]
Having this docker-compose.yml the app launch gives the following output.

``` yml
version: "3"
services:
  unit:
    image: nginx/unit:1.5-ruby2.3
    environment:
      - PORT=8001
    volumes:
      - './app:/app'
      - './config:/config'
    ports:
      - '8000:8000'
      - '8001:8001'
```

```
$ docker-compose up --force-recreate 
Pulling unit (nginx/unit:1.5-ruby2.3)...
1.5-ruby2.3: Pulling from nginx/unit
f17d81b4b692: Pull complete
f9f405c48f6f: Pull complete
1d3b63376d1f: Pull complete
Digest: sha256:7a579e0f7d9e52cda56b974bb06606f4c18bffeb88d1f67ed1fff1f1fde36b93
Status: Downloaded newer image for nginx/unit:1.5-ruby2.3
Creating unit_unit_1 ... done
Attaching to unit_unit_1
unit_1  | 2018/10/27 19:58:56 [info] 1#1 unit started
unit_1  | 2018/10/27 19:58:56 [info] 8#8 discovery started
unit_1  | 2018/10/27 19:58:56 [notice] 8#8 no modules matching: "/usr/lib/unit/modules/*.unit.so" found
unit_1  | 2018/10/27 19:58:56 [info] 9#9 controller started
unit_1  | 2018/10/27 19:58:56 [notice] 1#1 process 8 exited with code 0
unit_1  | 2018/10/27 19:58:56 [info] 10#10 router started
unit_1  | 2018/10/27 19:58:56 [info] 10#10 OpenSSL 1.1.0f  25 May 2017, 1010006f
```
Thus running ruby apps is not possible (this also happens with .full version)
Adding those lines (borrowed from Dockerfile.ruby2.3) makes the trick work
``` Dockerfile
ENV UNIT_VERSION 1.5-1~stretch
RUN echo "deb https://packages.nginx.org/unit/debian/ stretch unit" >> /etc/apt/sources.list.d/unit.list && \
    apt-get update  && \
    apt-get install -y unit=${UNIT_VERSION} unit-ruby=${UNIT_VERSION}

```
