### ISSUE TITLE
"detail": "The \"proxy\" address is invalid \"q1:8002\""   in  docker-compose

### ISSUE THREAD

**Issue by stfenjobs** [nginx/unit#421]
![image](https://user-images.githubusercontent.com/6580897/77915224-a9bdc280-72c9-11ea-9322-6b9ab3661f04.png)

when i use docker-compose,  i got the error

config.json
```
{

  "listeners": {
    "*:8008": {
        "pass": "routes"
    }
 },
  "routes": [
      {
          "match": {
              "host": "a.test.com"
          },

          "action": {
            "proxy": "http://q2:8001"
           }
      },
      {
        "match": {
            "host": "b.test.com"
        },

        "action": {
          "proxy": "http://q1:8002"
         }
    } 
   ]
}
```

**docker-compose.yml**
```
version: "3"
services:
  center:
    build: "center"
    restart: always
    expose:
      - 443/tcp
      - 80/tcp
    ports:
      - 8008:8008
    links:
      - q1
      - q2

  q1:
    build: "q1"
    ports:
      - 8001:8001
  q2:
    build: "q2"
    ports:
      - 8002:8002
```
