### ISSUE TITLE
YAML format for config

### ISSUE THREAD

**Issue by n0madic** [nginx/unit#73]
Is it possible to add YAML support for configs as more compact, intuitive and easier to edit?
It looks better 
```yaml
listeners:
  "*:8300":
    application: blogs
applications:
  blogs:
    type: php
    workers: 20
    root: /www/blogs/scripts
    index: index.php
```
than this
```json
{
    "listeners": {
        "*:8300": {
            "application": "blogs"
        }
    },

    "applications": {
        "blogs": {
            "type": "php",
            "workers": 20,
            "root": "/www/blogs/scripts",
            "index": "index.php"
        }
    }
}
```

Since JSON is a subset of YAML, it is possible to use both formats simultaneously.
