### ISSUE TITLE
Difference between unit upstream and nginx proxy_pass?

### ISSUE THREAD

**Issue by mercurykd** [nginx/unit#823]
hi i am using docker for my own dns server. I am connected to it through DoH. I use nginx proxy for ssl termination. Windows 11 successfully works under DoH.
doh.dockerfile
```
from nginx:stable
run apt update && \
apt install -y git net-tools && \
git clone https://github.com/TuxInvader/nginx-dns.git && \
cp -r ./nginx-dns/njs.d /etc/nginx/
```

docker-compose:
```
version: "3.7"

networks:
    default:
        ipam:
            config:
                - subnet: 10.10.0.0/24

services:
    doh:
        build:
            context: dockerfile
            dockerfile: doh.dockerfile
        volumes:
            - ./config/.profile:/root/.bashrc:ro
            - ./config/doh.conf:/etc/nginx/nginx.conf
            - ./certs/:/certs/
            - ./app/logs/:/var/log/nginx
        hostname: dnsoverhttps
        networks:
            default:
                ipv4_address: 10.10.0.6
        environment:
            TZ: ${TZ}
        stop_grace_period: 1s
    ng:
        build:
            context: dockerfile
            dockerfile: doh.dockerfile
        volumes:
            - ./config/.profile:/root/.bashrc:ro
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./certs/:/certs/
        ports:
            - 443:443
        hostname: nginx
        environment:
            TZ: ${TZ}
        stop_grace_period: 1s
        networks:
            default:
                ipv4_address: 10.10.0.4

```
doh.conf
```
user  nginx;
worker_processes  auto;

load_module modules/ngx_stream_js_module.so;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  # logging directives
  log_format  doh   '$remote_addr - $remote_user [$time_local] "$request" '
                    '[ $msec, $request_time, $upstream_response_time $pipe ] '
                    '$status $body_bytes_sent "$http_x_forwarded_for" '
                    '$upstream_http_x_dns_question $upstream_http_x_dns_type '
                    '$upstream_http_x_dns_result '
                    '$upstream_http_x_dns_ttl $upstream_http_x_dns_answers '
                    '$upstream_cache_status';

  access_log  /var/log/nginx/doh-access.log doh;

  # This upstream connects to a local Stream service which converts HTTP -> DNS
  upstream dohloop {
    zone dohloop 64k;
    server 127.0.0.1:8053;
    keepalive_timeout 60s;
    keepalive_requests 100;
    keepalive 10;
  }

  # Proxy Cache storage - so we can cache the DoH response from the upstream
  proxy_cache_path /var/cache/nginx/doh_cache levels=1:2 keys_zone=doh_cache:10m;

  # The DoH server block
  server {
    listen 80;

    # DoH may use GET or POST requests, Cache both
    proxy_cache_methods GET POST;

    # Return 404 to all responses, except for those using our published DoH URI
    location / {
      return 404 "404 Not Found\n";
    }

    # This is our published DoH URI
    location /dns-query {

      # Proxy HTTP/1.1, clear the connection header to enable Keep-Alive
      proxy_http_version 1.1;
      proxy_set_header Connection "";

      # Enable Cache, and set the cache_key to include the request_body
      proxy_cache doh_cache;
      proxy_cache_key $scheme$proxy_host$uri$is_args$args$request_body;

      # proxy pass to the dohloop upstream
      proxy_pass http://dohloop;
    }

  }

}

# DNS Stream Services
stream {

  # DNS logging
  log_format  dns   '$remote_addr [$time_local] $protocol "$dns_qname"';
  access_log /var/log/nginx/dns-access.log dns;

  # Import the NJS module
  js_import /etc/nginx/njs.d/dns/dns.js;

  # The $dns_qname variable can be populated by preread calls, and can be used for DNS routing
  js_set $dns_qname dns.get_qname;

  # DNS upstream pool.
  upstream dns {
    zone dns 64k;
    server 8.8.8.8:53;
  }

  # DNS over HTTPS (gateway) Service
  # Upstream can be either DNS(TCP) or DoT. If upstream is DNS, proxy_ssl should be off.
  server {
    listen 8053;
    js_filter dns.filter_doh_request;
    proxy_pass dns;
  }

}
```
nginx.conf
```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  server {
    listen 443 ssl http2;
    ssl_certificate /certs/letsencrypt.pem;
    ssl_certificate_key /certs/letsencrypt_key;


    location / {
      proxy_pass http://10.10.0.6:80;
    }

  }

}
```

If I put unit instead of nginx to terminate ssl, windows 11 stops working, DNS_PROBE_FINISHED_BAD_CONFIG
docker-compose:
```
version: "3.7"

networks:
    default:
        ipam:
            config:
                - subnet: 10.10.0.0/24

services:
    unit:
        image: nginx/unit:1.29.0-php8.1
        ports:
            - 443:443
        volumes:
            - ./config/unit.json:/docker-entrypoint.d/config.json
            - ./certs/letsencrypt.pem:/docker-entrypoint.d/letsencrypt.pem
        environment:
            TZ: ${TZ}
        hostname: unit
        restart: unless-stopped
        stop_grace_period: 1s
        networks:
            default:
                ipv4_address: 10.10.0.4
    doh:
        build:
            context: dockerfile
            dockerfile: doh.dockerfile
        volumes:
            - ./config/.profile:/root/.bashrc:ro
            - ./config/doh.conf:/etc/nginx/nginx.conf
            - ./certs/:/certs/
            - ./app/logs/:/var/log/nginx
        hostname: dnsoverhttps
        networks:
            default:
                ipv4_address: 10.10.0.6
        environment:
            TZ: ${TZ}
        stop_grace_period: 1s
```
unit:
```
{
    "listeners": {
        "*:443": {
            "pass": "upstreams/dns",
            "tls": {
                "certificate": "letsencrypt"
            }
        }
    },
    "upstreams": {
        "dns": {
            "servers": {
                "10.10.0.6:80": {}
            }
        }
    }
}
```
What is missing?
